### ISSUE TITLE
Prototype TODO

### ISSUE THREAD

**Issue by immortaleeb** [jeroenarens/Apps4Ghent_Bib#5]
**Deadline** 21/03 09:00

Frontend:
- [x] Draw statistical zones
- [x] Ajax calls to backend
- [x] Add slider for time
- [x] Add dots on map
- [x] Make map take up the whole page

Backend:
- [x] Implement simple API for frontend to use
- [x] Implement simple API to dump database

Importing:
- [x] Provide import scripts as backup for RML
- [x] RML conversion script
- [ ] Import all them data

Server:
- [x] Get basic production server up and running

Social stuff:
- [ ] Write down a plan for the minio...err... other students at Appsforghent to do our bidding... errr... help us adding features
